CREATE TABLE IF NOT EXISTS tenants(id uuid PRIMARY KEY, state jsonb NOT NULL, version integer NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), email text NOT NULL UNIQUE, name text NOT NULL, password text NOT NULL, role text NOT NULL CHECK(role IN ('owner','auditor')));
CREATE TABLE IF NOT EXISTS audit(id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), created_at timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS journals(id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), created_at timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS requests(tenant_id uuid NOT NULL REFERENCES tenants(id), request_key text NOT NULL, fingerprint text NOT NULL, PRIMARY KEY(tenant_id,request_key));
CREATE INDEX IF NOT EXISTS audit_tenant ON audit(tenant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS journals_tenant ON journals(tenant_id,created_at DESC);
CREATE OR REPLACE FUNCTION reject_ledger_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Posted ledger records are append-only'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit FOR EACH ROW EXECUTE FUNCTION reject_ledger_change();
CREATE TRIGGER journals_immutable BEFORE UPDATE OR DELETE ON journals FOR EACH ROW EXECUTE FUNCTION reject_ledger_change();
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON tenants USING(id=nullif(current_setting('app.tenant_id',true),'')::uuid) WITH CHECK(id=nullif(current_setting('app.tenant_id',true),'')::uuid);
ALTER TABLE audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit FORCE ROW LEVEL SECURITY;
CREATE POLICY audit_scope ON audit USING(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid) WITH CHECK(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid);
ALTER TABLE journals ENABLE ROW LEVEL SECURITY;
ALTER TABLE journals FORCE ROW LEVEL SECURITY;
CREATE POLICY journal_scope ON journals USING(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid) WITH CHECK(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid);
ALTER TABLE requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE requests FORCE ROW LEVEL SECURITY;
CREATE POLICY request_scope ON requests USING(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid) WITH CHECK(tenant_id=nullif(current_setting('app.tenant_id',true),'')::uuid);
