import { useEffect, useState } from 'react'
import { request } from './api'
type Connector={id:string;category:string;provider:string;status:string;configuration:Record<string,string>}
export function ConnectorsPanel({csrf,plan}:{csrf:string;plan?:string}){
 const [items,setItems]=useState<Connector[]>([]),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>request<{connectors:Connector[]}>('/connectors').then(x=>setItems(x.connectors)).catch(e=>setError(e.message))
 useEffect(()=>{void load()},[])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await request('/connectors',{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({category:f.get('category'),provider:f.get('provider'),status:f.get('status'),configuration:{sender:String(f.get('sender')||''),webhookUrl:String(f.get('webhookUrl')||'')},credentials:f.get('apiKey')?{apiKey:String(f.get('apiKey'))}:undefined})});e.currentTarget.reset();setMessage('Connector saved. Credentials are encrypted and hidden.');await load()}catch(x){setError(x instanceof Error?x.message:'Could not save connector.')}finally{setBusy(false)}}
 return <section className="card"><h2>Tenant provider connectors</h2><p>Configure each provider per tenant. Bank feeds require Enterprise; use sandbox for 3PL before production.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form className="operations-fields" onSubmit={e=>void submit(e)}><label>Category<select name="category" defaultValue="email"><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="payment">Payment gateway</option><option value="three_pl">3PL logistics</option>{plan==='enterprise'&&<option value="bank_feed">Live bank feed</option>}</select></label><label>Provider<input name="provider" required placeholder="e.g. SendGrid, Twilio, Meta"/></label><label>Status<select name="status"><option value="draft">Draft</option><option value="sandbox">Sandbox</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label>Sender / account ID<input name="sender"/></label><label>Webhook URL<input name="webhookUrl" type="url"/></label><label>API key / secret<input name="apiKey" type="password" autoComplete="new-password"/></label><button className="primary" disabled={busy}>{busy?'Saving...':'Save connector'}</button></form><div className="table-scroll"><table><thead><tr><th>Category</th><th>Provider</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.category}</td><td>{x.provider}</td><td>{x.status}</td></tr>)}{!items.length&&<tr><td colSpan={3}>No connectors configured.</td></tr>}</tbody></table></div></section>
}
