import { useState } from 'react'
import type {Action,State,StockMovement} from './types'
import {inventoryValue} from './inventory'
const labels:Record<StockMovement['kind'],string>={baseline:'Opening snapshot',opening:'Product opening',receipt:'Purchase receipt',adjustment:'Adjustment',count:'Physical count',fulfillment:'Customer fulfillment',return:'Customer return'}
export function StockPanel({state,search,busy,readOnly,onCommit,onPurchasing}:{state:State;search:string;busy:boolean;readOnly:boolean;onCommit:(a:Action)=>Promise<boolean>;onPurchasing:()=>void}){
 const [mode,setMode]=useState<'stock_adjust'|'stock_count'>('stock_adjust'),[product,setProduct]=useState(''),[expected,setExpected]=useState<number|null>(null),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[kind,setKind]=useState('all')
 const p=state.products.find(p=>p.id===product),number=quantity.trim()===''?null:Number(quantity),after=number===null||expected===null?null:mode==='stock_count'?number:expected+number,delta=after===null||expected===null?null:after-expected
 const stale=!!p&&expected!==p.qty
 const money=(n:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:state.currency,maximumFractionDigits:2}).format(n)
 let value:number|null=null
 try{if(delta!==null&&p)value=inventoryValue(delta,p.cost)}catch{/* Invalid previews are rejected by form and domain validation. */}
 const rows=(state.stockMovements||[]).filter(m=>(kind==='all'||m.kind===kind)&&[m.productName,m.sku,m.reason,m.source,m.actor].some(v=>v.toLowerCase().includes(search.toLowerCase())))
 function exportHistory(){const escape=(v:unknown)=>{let s=String(v);if(/^[=+@\-\t\r]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const data=[['Date (UTC)','Product','SKU','Type','Before','Change','After','Unit cost','Value change','Reason','Source','Actor'],...rows.map(m=>[m.date,m.productName,m.sku,labels[m.kind],m.before,m.delta,m.after,m.unitCost,m.valueDelta,m.reason,m.source,m.actor])].map(r=>r.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='businessos-stock-movements.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <>
 <section className="card"><div className="section-top"><h2>Stock control</h2><button onClick={onPurchasing}>Receive a purchase order →</button></div><p>Use an adjustment for damage, loss or corrections. Record a physical count to compare counted stock with the expected quantity.</p>{!state.products.length?<p className="empty">Add a product before recording stock changes.</p>:<form onSubmit={async e=>{e.preventDefault();if(!p||expected===null||stale)return;const ok=await onCommit({type:mode,data:{product:p.id,expectedQty:expected,reason,...(mode==='stock_adjust'?{delta:quantity}:{counted:quantity})}});if(ok){setExpected(after);setQuantity('');setReason('')}}}><fieldset disabled={busy||readOnly} className="stock-form"><label>Operation<select value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setQuantity('')}}><option value="stock_adjust">Adjust stock</option><option value="stock_count">Record physical count</option></select></label><label>Product<select required value={product} onChange={e=>{setProduct(e.target.value);setExpected(state.products.find(p=>p.id===e.target.value)?.qty??null);setQuantity('')}}><option value="">Select a product</option>{state.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label>{mode==='stock_adjust'?'Quantity change (negative to remove)':'Counted quantity'}<input required type="number" step="1" min={mode==='stock_count'?0:-100000000} max="100000000" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Reason<textarea required minLength={3} maxLength={500} value={reason} placeholder="For example: 2 damaged units found during inspection" onChange={e=>setReason(e.target.value)}/></label>{p&&<div className="stock-preview"><span>Expected stock <b>{expected}</b></span><span>Resulting stock <b>{after??'—'}</b></span><span>Inventory value change <b>{value===null?'—':money(value)}</b></span></div>}{stale&&<div className="alert" role="alert">Stock changed to {p?.qty} units. Review your entry before continuing.<button type="button" onClick={()=>setExpected(p?.qty??null)}>Use latest stock</button></div>}<p className="footnote">Changes use the recorded unit cost. A decrease posts inventory adjustment expense; an increase posts inventory adjustment gain. A matching count records evidence without a financial posting.</p><button className="primary" disabled={!p||stale||after===null||after<0||after>100000000||value===null||(mode==='stock_adjust'&&number===0)}>{busy?'Saving...':mode==='stock_adjust'?'Post adjustment':'Save physical count'}</button></fieldset></form>}</section>
 <section className="card"><div className="section-top"><h2>Stock movement history</h2><div className="history-controls"><select aria-label="Movement type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All movements</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button onClick={exportHistory} disabled={!rows.length}>Export movements</button></div></div><div className="table-scroll"><table><thead><tr>{['Date','Product','Type','Before','Change','After','Value change','Details'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{new Date(m.date).toLocaleString()}</td><td>{m.productName}<br/><small>{m.sku}</small></td><td>{labels[m.kind]}</td><td>{m.before}</td><td>{m.delta>0?'+':''}{m.delta}</td><td>{m.after}</td><td>{money(m.valueDelta)}</td><td className="movement-details"><details><summary>{m.reason.length>55?m.reason.slice(0,55)+'…':m.reason}</summary><p>{m.reason}</p><small>Unit cost: {money(m.unitCost)}<br/>Actor: {m.actor}<br/>Source: {m.source}</small></details></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No movements match your search.</p>}</div><p className="footnote">Opening snapshots preserve existing quantities; they do not reconstruct earlier transactions. Server movements are append-only. Correct errors with a new adjustment.</p></section>
 </>
}
